[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "AEQUITAS"
authors = [{name = "Roberta Calegari", email = "roberta.calegari@unibo.it"},
{name = "Andrea Borghesi", email = "andrea.borghesi3@unibo.it"}]
dynamic = ["version", "description"]
